image: debian/stable
sources:
 - https://git.sr.ht/~marcevanstein/scamp_extensions
environment:
 GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
secrets:
 - 9daf0a17-ac84-4185-8851-3464007a3615
tasks:
 - mirror: |
     cd scamp_extensions
     git remote add github git@github.com:MarcTheSpark/scamp_extensions.git
     git push github --all --follow-tags