[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scamp_extensions"
version = "0.4.0"
description = "Extensions to SCAMP (Suite for Computer-Assisted Music in Python)"
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-only"

authors = [
    { name = "Marc Evanstein", email = "marc@marcevanstein.com" }
]

dependencies = [
    "scamp>=0.13.0",
    "expenvelope>=0.8.0",
    "clockblocks>=1.0.0",
    "numpy",
    "mido"
]

[project.optional-dependencies]
engraving = ["drawsvg"]

[project.urls]
"Source Code" = "https://github.com/MarcTheSpark/scamp_extensions"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
scamp_extensions = [
    "playback/supercollider/*.scd",
    "playback/supercollider/*.yaml",
    "playback/supercollider/scampExtensions/*"
]
